### ISSUE TITLE
get_lines() SportsBookReview website outdated.

### ISSUE THREAD

**Issue by maschepps** [papagorgio23/bettoR#13]
Hi, I have attempted your get_lines() function for the NBA, e.g. 
```
get_lines(
+     sport = "NBA",
+     bet_type = "total",
+     period = "2Q",
+     start_date = "20191221"
+ )
```
and receive the error
`Error in teams[[1]] : subscript out of bounds
`

After inspection it appears the oddsURL is outdated.
`  oddsURL <-
    glue::glue(
      "https://classic.sportsbookreview.com/betting-odds/{SPORT}/{TYPE}/{PERIOD}/?date={DATE}"
    )
`I have attempted to manually fix this, but am unsuccessful.

**Comment by papagorgio23** [comment]
This function is outdated. Unfortunately, I will have to remove this function from this package in the next update. I am looking into providing this data as csv files so we aren't overwhelming the websites with scrapes. I'm not sure the timetable for that though. Hopefully this offseason I will be able to finish it.

**Comment by papagorgio23** [comment]
Issue has been resolved for the time being by removing the functions completely from the package with this commit https://github.com/papagorgio23/bettoR/commit/9038be03430befc3c273fba578dc008dcc32ecda. Future work will be to bring it back.
