### ISSUE TITLE
Could you add a rounding argument to each function?

### ISSUE THREAD

**Issue by aaronmorrisNC** [papagorgio23/bettoR#14]
First of all, the bettoR package is great and works like a charm.  However, it would be helpful if rounding was added as an argument to the function.  Perhaps an argument that specifies the number of decimal places or even turn off rounding all together.  There are many instances where it is valuable to not round results.  If you could add this functionality to all of the bettoR functions it would be extremely useful.

    true_prob <-
      round(implied_prob(odds = line, type = type) / sum(implied_prob(odds = odds, type = type)), 4)

    fair_odds <- implied_odds(true_prob, type = type)

    return(fair_odds)
  }
#

**Comment by papagorgio23** [comment]
I'm glad you're enjoying the package. I completely agree with you that these calculations shouldn't be rounded internally. The onus will be on the user to round how they see fit. I went ahead and removed the rounding. Thanks for bringing it to my attention.

This issue has been resolved with https://github.com/papagorgio23/bettoR/commit/5edefe38ca965151b29cc7b2fc8827c460f845dc
